// src/stores/projects.ts
import { Project } from './types';

export const projects: Project[] = [
  {
    name: 'layout',
    isActive: true,
    components: [
      'ButterflyHomePage',
      'ErrorScreen',
      // 'UnderConstruction',
      // 'TitleBar',
      // 'NavigationMenu',
      // 'AccordionGallery',
      // 'RandomText',
      // 'RandomImage',
      // 'TextInput',
      // 'ChatInterface',
      // 'VoiceControl',
      // 'UserLogin',
      // 'SettingsPanel',
    ],
  },
  {
    name: 'screenfx',
    isActive: false,
    components: [
      'MagicRemote',
      'ButterflyMascot',
      // 'LavaBubble',
      // 'LavaLamp',
      // 'MagicFrame',
      // 'RainEffect',
      // 'SoapBubbles',
      // 'SplashImage',
    ],
  },
  {
    name: 'artgallery',
    isActive: false,
    components: ['ArtGallery', 'GiftShop', 'MembershipClub', 'ShoppingCart'],
  },
  {
    name: 'assetmanager',
    isActive: false,
    components: [
      'AssetManager',
      'EffectsManager',
      'ToyboxManager',
      'ArtManager',
      'GameManager',
      'PromptDesigner',
      'ProjectManager',
      'CardDesigner',
      'CodeDesigner',
      'ApiManager',
      'SiteDesigner',
      'GalleryDesigner',
      'TaskManager',
    ],
  },
  {
    name: 'codecards',
    isActive: false,
    components: [
      'CodeCard',
      'AvatarCard',
      'UserCard',
      'RobotCard',
      'ChatGPTCard',
      'PromptCard',
      'ArtistCard',
      'ArtCard',
      'AlexaCard',
    ],
  },
  {
    name: 'gamescreen',
    isActive: false,
    components: [
      'GameScreen',
      'MiniPlanet',
      'ChatBot',
      'ArtAcademy',
      'AdventurePanel',
      'CosmosGame',
      'SerendipityGame',
    ],
  },
];
